# Generated by Django 5.1 on 2025-11-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escueladanza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('uso', models.CharField(blank=True, max_length=100)),
                ('equipo_disponible', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='clases', to='app_escueladanza.alumno'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app_escueladanza.profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app_escueladanza.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app_escueladanza.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='app_escueladanza.salon'),
        ),
    ]
